version: '3.1'

services:
  react-app:
    container_name: react-app
    build:
      context: ./react-app
      dockerfile: ./Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - ./react-app:/app
      - react-app-node_modules:/app/node_modules
    environment:
      - NODE_ENV=development

  graphql:
    container_name: graphql
    restart: always
    build:
      context: ./graphql
      dockerfile: ./Dockerfile
    ports:
      - "5001:5000"
    volumes:
      - ./graphql:/app

  mysql:
    container_name: mysql
    image: mysql:latest
    restart: always
    ports:
      - "33061:3306"
    command:
      [
        "mysqld",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_bin"
      ]
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: employees

networks:
  default:
    name: graphql-practice

volumes:
  react-app-node_modules: